name: CI Feature Branch

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  build-and-test:
    # maquina virtual Ubuntu que executa o job
    runs-on: ubuntu-latest
    steps:
      # Checkout do codigo da branch atual
      - name: Checkout code
        uses: actions/checkout@v4

      # Configuração do python comk a versão 3 pra cima
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Notificar caso o teste falhe
      - name: Notify failure
        if: failure()
        run: echo "Unit _tests_ failed. Please check the logs."
